INSERT INTO `country` VALUES ('ABW','Aruba','North America', 129);
INSERT INTO `country` VALUES ('AFG','Afghanistan','Asia', 1);
INSERT INTO `country` VALUES ('AGO','Angola','Africa', 56);
INSERT INTO `country` VALUES ('AIA','Anguilla','North America', 62);
INSERT INTO `country` VALUES ('ALB','Albania','Europe', 34);
INSERT INTO `country` VALUES ('AND','Andorra','Europe', 55);
INSERT INTO `country` VALUES ('ANT','Netherlands Antilles','North America', 33);
INSERT INTO `country` VALUES ('ARE','United Arab Emirates','Asia', 65);
INSERT INTO `country` VALUES ('ARG','Argentina','South America',69);
INSERT INTO `country` VALUES ('ARM','Armenia','Asia', 126);
INSERT INTO `country` VALUES ('ASM','American Samoa','Oceania',54);
INSERT INTO `country` VALUES ('ATA','Antarctica','Antarctica', NULL);
INSERT INTO `country` VALUES ('ATF','French Southern territories','Antarctica', NULL);
INSERT INTO `country` VALUES ('ATG','Antigua and Barbuda','North America', 63);
INSERT INTO `country` VALUES ('AUS','Australia','Oceania', 135);
INSERT INTO `country` VALUES ('AUT', 'Austria', 'Europe', 1523);
INSERT INTO `country` VALUES ('AZE', 'Azerbaijan', 'Asia', 144);
INSERT INTO `country` VALUES ('BDI', 'Burundi', 'Africa', 552);
INSERT INTO `country` VALUES ('BEL', 'Belgium', 'Europe', 179);
INSERT INTO `country` VALUES ('BEN', 'Benin', 'Africa', 187);
INSERT INTO `country` VALUES ('BFA', 'Burkina Faso', 'Africa', 549);
INSERT INTO `country` VALUES ('BGD', 'Bangladesh', 'Asia', 150);
INSERT INTO `country` VALUES ('BGR', 'Bulgaria', 'Europe', 539);
INSERT INTO `country` VALUES ('BHR', 'Bahrain', 'Asia', 149);
INSERT INTO `country` VALUES ('BHS', 'Bahamas', 'North America', 148);
INSERT INTO `country` VALUES ('BIH', 'Bosnia and Herzegovina', 'Europe', 201);
INSERT INTO `country` VALUES ('BLR', 'Belarus', 'Europe', 3520);
INSERT INTO `country` VALUES ('BLZ', 'Belize', 'North America', 185);
INSERT INTO `country` VALUES ('BMU', 'Bermuda', 'North America', 191);
INSERT INTO `country` VALUES ('BOL', 'Bolivia', 'South America', 194);
INSERT INTO `country` VALUES ('BRA', 'Brazil', 'South America', 211);
INSERT INTO `country` VALUES ('BRB', 'Barbados', 'North America', 174);
INSERT INTO `country` VALUES ('BRN', 'Brunei', 'Asia', 538);
INSERT INTO `country` VALUES ('BTN', 'Bhutan', 'Asia', 192);
INSERT INTO `country` VALUES ('BVT', 'Bouvet Island', 'Antarctica', NULL);
INSERT INTO `country` VALUES ('BWA', 'Botswana', 'Africa', 204);
INSERT INTO `country` VALUES ('CAF', 'Central African Republic', 'Africa', 1889);
INSERT INTO `country` VALUES ('CAN', 'Canada', 'North America', 1822);
INSERT INTO `country` VALUES ('CCK', 'Cocos (Keeling) Islands', 'Oceania', 2317);
INSERT INTO `country` VALUES ('CHE', 'Switzerland', 'Europe', 3248);
INSERT INTO `country` VALUES ('CHL', 'Chile', 'South America', 554);
INSERT INTO `country` VALUES ('CHN', 'China', 'Asia', 1891);
INSERT INTO `country` VALUES ('CIV', 'Côte dIvoire', 'Africa', 2814);
INSERT INTO `country` VALUES ('CMR', 'Cameroon', 'Africa', 1804);
INSERT INTO `country` VALUES ('COD', 'Congo',  'Africa', 2298);
INSERT INTO `country` VALUES ('COG', 'Congo', 'Africa', 2296);
INSERT INTO `country` VALUES ('COK', 'Cook Islands', 'Oceania', 583);
INSERT INTO `country` VALUES ('COL', 'Colombia', 'South America', 2257);
INSERT INTO `country` VALUES ('COM', 'Comoros', 'Africa', 2295);
INSERT INTO `country` VALUES ('CPV', 'Cape Verde', 'Africa', 1859);
INSERT INTO `country` VALUES ('CRI', 'Costa Rica', 'North America', 584);
INSERT INTO `country` VALUES ('CUB', 'Cuba', 'North America', 2413);
INSERT INTO `country` VALUES ('CXR', 'Christmas Island', 'Oceania', 1791);
INSERT INTO `country` VALUES ('CYM', 'Cayman Islands', 'North America', 553);
INSERT INTO `country` VALUES ('CYP', 'Cyprus', 'Asia', 2430);
INSERT INTO `country` VALUES ('CZE', 'Czech Republic', 'Europe', 3339);
INSERT INTO `country` VALUES ('DEU', 'Germany', 'Europe', 3068);
INSERT INTO `country` VALUES ('DJI', 'Djibouti', 'Africa', 585);
INSERT INTO `country` VALUES ('DMA', 'Dominica', 'North America', 586);
INSERT INTO `country` VALUES ('DNK', 'Denmark', 'Europe', 3315);
INSERT INTO `country` VALUES ('DOM', 'Dominican Republic', 'North America', 587);
INSERT INTO `country` VALUES ('DZA', 'Algeria', 'Africa', 35);
INSERT INTO `country` VALUES ('ECU', 'Ecuador', 'South America', 594);
INSERT INTO `country` VALUES ('EGY', 'Egypt', 'Africa', 608);
INSERT INTO `country` VALUES ('ERI', 'Eritrea', 'Africa', 652);
INSERT INTO `country` VALUES ('ESH', 'Western Sahara', 'Africa', 2453);
INSERT INTO `country` VALUES ('ESP', 'Spain', 'Europe', 653);
INSERT INTO `country` VALUES ('EST', 'Estonia', 'Europe', 3791);
INSERT INTO `country` VALUES ('ETH', 'Ethiopia', 'Africa', 756);
INSERT INTO `country` VALUES ('FIN', 'Finland', 'Europe', 3236);
INSERT INTO `country` VALUES ('FJI', 'Fiji Islands', 'Oceania', 764);
INSERT INTO `country` VALUES ('FLK', 'Falkland Islands', 'South America', 763);
INSERT INTO `country` VALUES ('FRA', 'France', 'Europe', 2974);
INSERT INTO `country` VALUES ('FRO', 'Faroe Islands', 'Europe', 901);
INSERT INTO `country` VALUES ('FSM', 'Micronesia',  'Oceania', 2689);
INSERT INTO `country` VALUES ('GAB', 'Gabon', 'Africa', 902);
INSERT INTO `country` VALUES ('GBR', 'United Kingdom', 'Europe', 456);
INSERT INTO `country` VALUES ('GEO', 'Georgia', 'Asia', 905);
INSERT INTO `country` VALUES ('GHA', 'Ghana', 'Africa', 910);
INSERT INTO `country` VALUES ('GIB', 'Gibraltar', 'Europe', 915);
INSERT INTO `country` VALUES ('GIN', 'Guinea', 'Africa', 926);
INSERT INTO `country` VALUES ('GLP', 'Guadeloupe', 'North America', 919);
INSERT INTO `country` VALUES ('GMB', 'Gambia', 'Africa', 904);
INSERT INTO `country` VALUES ('GNB', 'Guinea-Bissau', 'Africa', 927);
INSERT INTO `country` VALUES ('GNQ', 'Equatorial Guinea', 'Africa', 2972);
INSERT INTO `country` VALUES ('GRC', 'Greece', 'Europe', 2401);
INSERT INTO `country` VALUES ('GRD', 'Grenada', 'North America', 916);
INSERT INTO `country` VALUES ('GRL', 'Greenland', 'North America', 917);
INSERT INTO `country` VALUES ('GTM', 'Guatemala', 'North America', 922);
INSERT INTO `country` VALUES ('GUF', 'French Guiana', 'South America', 3014);
INSERT INTO `country` VALUES ('GUM', 'Guam', 'Oceania', 921);
INSERT INTO `country` VALUES ('GUY', 'Guyana', 'South America', 928);
INSERT INTO `country` VALUES ('HKG', 'Hong Kong', 'Asia', 937);
INSERT INTO `country` VALUES ('HMD', 'Heard Island and McDonald Islands', 'Antarctica', NULL);
INSERT INTO `country` VALUES ('HND', 'Honduras', 'North America', 933);
INSERT INTO `country` VALUES ('HRV', 'Croatia', 'Europe', 2409);
INSERT INTO `country` VALUES ('HTI', 'Haiti', 'North America', 929);
INSERT INTO `country` VALUES ('HUN', 'Hungary', 'Europe', 3483);
INSERT INTO `country` VALUES ('IDN', 'Indonesia', 'Asia', 939);
INSERT INTO `country` VALUES ('IND', 'India', 'Asia', 1109);
INSERT INTO `country` VALUES ('IOT', 'British Indian Ocean Territory', 'Africa', NULL);
INSERT INTO `country` VALUES ('IRL', 'Ireland', 'Europe', 1447);
INSERT INTO `country` VALUES ('IRN', 'Iran', 'Asia', 1380);
INSERT INTO `country` VALUES ('IRQ', 'Iraq', 'Asia', 1365);
INSERT INTO `country` VALUES ('ISL', 'Iceland', 'Europe', 1449);
INSERT INTO `country` VALUES ('ISR', 'Israel', 'Asia', 1450);
INSERT INTO `country` VALUES ('ITA', 'Italy', 'Europe', 1464);
INSERT INTO `country` VALUES ('JAM', 'Jamaica', 'North America', 1530);
INSERT INTO `country` VALUES ('JOR', 'Jordan', 'Asia', 1786);
INSERT INTO `country` VALUES ('JPN', 'Japan', 'Asia', 1532);
INSERT INTO `country` VALUES ('KAZ', 'Kazakstan', 'Asia', 1864);
INSERT INTO `country` VALUES ('KEN', 'Kenya', 'Africa', 1881);
INSERT INTO `country` VALUES ('KGZ', 'Kyrgyzstan', 'Asia', 2253);
INSERT INTO `country` VALUES ('KHM', 'Cambodia', 'Asia', 1800);
INSERT INTO `country` VALUES ('KIR', 'Kiribati', 'Oceania', 2256);
INSERT INTO `country` VALUES ('KNA', 'Saint Kitts and Nevis', 'North America', 3064);
INSERT INTO `country` VALUES ('KOR', 'South Korea', 'Asia', 2331);
INSERT INTO `country` VALUES ('KWT', 'Kuwait', 'Asia', 2429);
INSERT INTO `country` VALUES ('LAO', 'Laos', 'Asia', 2432);
INSERT INTO `country` VALUES ('LBN', 'Lebanon', 'Asia', 2438);
INSERT INTO `country` VALUES ('LBR', 'Liberia', 'Africa', 2440);
INSERT INTO `country` VALUES ('LBY', 'Libyan Arab Jamahiriya', 'Africa', 2441);
INSERT INTO `country` VALUES ('LCA', 'Saint Lucia', 'North America', 3065);
INSERT INTO `country` VALUES ('LIE', 'Liechtenstein', 'Europe', 2446);
INSERT INTO `country` VALUES ('LKA', 'Sri Lanka', 'Asia', 3217);
INSERT INTO `country` VALUES ('LSO', 'Lesotho', 'Africa', 2437);
INSERT INTO `country` VALUES ('LTU', 'Lithuania', 'Europe', 2447);
INSERT INTO `country` VALUES ('LUX', 'Luxembourg', 'Europe', 2452);
INSERT INTO `country` VALUES ('LVA', 'Latvia', 'Europe', 2434);
INSERT INTO `country` VALUES ('MAC', 'Macao', 'Asia', 2454);
INSERT INTO `country` VALUES ('MAR', 'Morocco', 'Africa', 2486);
INSERT INTO `country` VALUES ('MCO', 'Monaco', 'Europe', 2695);
INSERT INTO `country` VALUES ('MDA', 'Moldova', 'Europe', 2690);
INSERT INTO `country` VALUES ('MDG', 'Madagascar', 'Africa', 2455);
INSERT INTO `country` VALUES ('MDV', 'Maldives', 'Asia', 2463);
INSERT INTO `country` VALUES ('MEX', 'Mexico', 'North America', 2515);
INSERT INTO `country` VALUES ('MHL', 'Marshall Islands', 'Oceania', 2507);
INSERT INTO `country` VALUES ('MKD', 'Macedonia', 'Europe', 2460);
INSERT INTO `country` VALUES ('MLI', 'Mali', 'Africa', 2482);
INSERT INTO `country` VALUES ('MLT', 'Malta', 'Europe', 2484);
INSERT INTO `country` VALUES ('MMR', 'Myanmar', 'Asia', 2710);
INSERT INTO `country` VALUES ('MNG', 'Mongolia', 'Asia', 2696);
INSERT INTO `country` VALUES ('MNP', 'Northern Mariana Islands', 'Oceania', 2913);
INSERT INTO `country` VALUES ('MOZ', 'Mozambique', 'Africa', 2698);
INSERT INTO `country` VALUES ('MRT', 'Mauritania', 'Africa', 2509);
INSERT INTO `country` VALUES ('MSR', 'Montserrat', 'North America', 2697);
INSERT INTO `country` VALUES ('MTQ', 'Martinique', 'North America', 2508);
INSERT INTO `country` VALUES ('MUS', 'Mauritius', 'Africa', 2511);
INSERT INTO `country` VALUES ('MWI', 'Malawi', 'Africa', 2462);
INSERT INTO `country` VALUES ('MYS', 'Malaysia', 'Asia', 2464);
INSERT INTO `country` VALUES ('MYT', 'Mayotte', 'Africa', 2514);
INSERT INTO `country` VALUES ('NAM', 'Namibia', 'Africa', 2726);
INSERT INTO `country` VALUES ('NCL', 'New Caledonia', 'Oceania', 3493);
INSERT INTO `country` VALUES ('NER', 'Niger', 'Africa', 2738);
INSERT INTO `country` VALUES ('NFK', 'Norfolk Island', 'Oceania', 2806);
INSERT INTO `country` VALUES ('NGA', 'Nigeria', 'Africa', 2754);
INSERT INTO `country` VALUES ('NIC', 'Nicaragua', 'North America', 2734);
INSERT INTO `country` VALUES ('NIU', 'Niue', 'Oceania', 2805);
INSERT INTO `country` VALUES ('NLD', 'Netherlands', 'Europe', 5);
INSERT INTO `country` VALUES ('NOR', 'Norway', 'Europe', 2807);
INSERT INTO `country` VALUES ('NPL', 'Nepal', 'Asia', 2729);
INSERT INTO `country` VALUES ('NRU', 'Nauru', 'Oceania', 2728);
INSERT INTO `country` VALUES ('NZL', 'New Zealand', 'Oceania', 3499);
INSERT INTO `country` VALUES ('OMN', 'Oman', 'Asia', 2821);
INSERT INTO `country` VALUES ('PAK', 'Pakistan', 'Asia', 2831);
INSERT INTO `country` VALUES ('PAN', 'Panama', 'North America', 2882);
INSERT INTO `country` VALUES ('PCN', 'Pitcairn', 'Oceania', 2912);
INSERT INTO `country` VALUES ('PER', 'Peru', 'South America', 2890);
INSERT INTO `country` VALUES ('PHL', 'Philippines', 'Asia', 766);
INSERT INTO `country` VALUES ('PLW', 'Palau', 'Oceania', 2881);
INSERT INTO `country` VALUES ('PNG', 'Papua New Guinea', 'Oceania', 2884);
INSERT INTO `country` VALUES ('POL', 'Poland', 'Europe', 2928);
INSERT INTO `country` VALUES ('PRI', 'Puerto Rico', 'North America', 2919);
INSERT INTO `country` VALUES ('PRK', 'North Korea', 'Asia', 2318);
INSERT INTO `country` VALUES ('PRT', 'Portugal', 'Europe', 2914);
INSERT INTO `country` VALUES ('PRY', 'Paraguay', 'South America', 2885);
INSERT INTO `country` VALUES ('PSE', 'Palestine', 'Asia', 4074);
INSERT INTO `country` VALUES ('PYF', 'French Polynesia', 'Oceania', 3016);
INSERT INTO `country` VALUES ('QAT', 'Qatar', 'Asia', 2973);
INSERT INTO `country` VALUES ('REU', 'Réunion', 'Africa', 3017);
INSERT INTO `country` VALUES ('ROM', 'Romania', 'Europe', 3018);
INSERT INTO `country` VALUES ('RUS', 'Russian Federation', 'Europe', 3580);
INSERT INTO `country` VALUES ('RWA', 'Rwanda', 'Africa', 3047);
INSERT INTO `country` VALUES ('SAU', 'Saudi Arabia', 'Asia', 3173);
INSERT INTO `country` VALUES ('SDN', 'Sudan', 'Africa', 3225);
INSERT INTO `country` VALUES ('SEN', 'Senegal', 'Africa', 3198);
INSERT INTO `country` VALUES ('SGP', 'Singapore', 'Asia', 3208);
INSERT INTO `country` VALUES ('SGS', 'South Georgia and the South Sandwich Islands', 'Antarctica', NULL);
INSERT INTO `country` VALUES ('SHN', 'Saint Helena', 'Africa', 3063);
INSERT INTO `country` VALUES ('SJM', 'Svalbard and Jan Mayen', 'Europe', 938);
INSERT INTO `country` VALUES ('SLB', 'Solomon Islands', 'Oceania', 3161);
INSERT INTO `country` VALUES ('SLE', 'Sierra Leone', 'Africa', 3207);
INSERT INTO `country` VALUES ('SLV', 'El Salvador', 'North America', 645);
INSERT INTO `country` VALUES ('SMR', 'San Marino', 'Europe', 3171);
INSERT INTO `country` VALUES ('SOM', 'Somalia', 'Africa', 3214);
INSERT INTO `country` VALUES ('SPM', 'Saint Pierre and Miquelon', 'North America', 3067);
INSERT INTO `country` VALUES ('STP', 'Sao Tome and Principe', 'Africa', 3172);
INSERT INTO `country` VALUES ('SUR', 'Suriname', 'South America', 3243);
INSERT INTO `country` VALUES ('SVK', 'Slovakia', 'Europe', 3209);
INSERT INTO `country` VALUES ('SVN', 'Slovenia', 'Europe', 3212);
INSERT INTO `country` VALUES ('SWE', 'Sweden', 'Europe', 3048);
INSERT INTO `country` VALUES ('SWZ', 'Swaziland', 'Africa', 3244);
INSERT INTO `country` VALUES ('SYC', 'Seychelles', 'Africa', 3206);
INSERT INTO `country` VALUES ('SYR', 'Syria', 'Asia', 3250);
INSERT INTO `country` VALUES ('TCA', 'Turks and Caicos Islands', 'North America', 3423);
INSERT INTO `country` VALUES ('TCD', 'Chad', 'Africa', 3337);
INSERT INTO `country` VALUES ('TGO', 'Togo', 'Africa', 3332);
INSERT INTO `country` VALUES ('THA', 'Thailand', 'Asia', 3320);
INSERT INTO `country` VALUES ('TJK', 'Tajikistan', 'Asia', 3261);
INSERT INTO `country` VALUES ('TKL', 'Tokelau', 'Oceania', 3333);
INSERT INTO `country` VALUES ('TKM', 'Turkmenistan', 'Asia', 3419);
INSERT INTO `country` VALUES ('TMP', 'East Timor', 'Asia', 1522);
INSERT INTO `country` VALUES ('TON', 'Tonga', 'Oceania', 3334);
INSERT INTO `country` VALUES ('TTO', 'Trinidad and Tobago', 'North America', 3336);
INSERT INTO `country` VALUES ('TUN', 'Tunisia', 'Africa', 3349);
INSERT INTO `country` VALUES ('TUR', 'Turkey', 'Asia', 3358);
INSERT INTO `country` VALUES ('TUV', 'Tuvalu', 'Oceania', 3424);
INSERT INTO `country` VALUES ('TWN', 'Taiwan', 'Asia', 3263);
INSERT INTO `country` VALUES ('TZA', 'Tanzania', 'Africa', 3306);
INSERT INTO `country` VALUES ('UGA', 'Uganda', 'Africa', 3425);
INSERT INTO `country` VALUES ('UKR', 'Ukraine', 'Europe', 3426);
INSERT INTO `country` VALUES ('UMI', 'United States Minor Outlying Islands', 'Oceania', NULL);
INSERT INTO `country` VALUES ('URY', 'Uruguay', 'South America', 3492);
INSERT INTO `country` VALUES ('USA', 'United States', 'North America', 3813);
INSERT INTO `country` VALUES ('UZB', 'Uzbekistan', 'Asia', 3503);
INSERT INTO `country` VALUES ('VAT', 'Holy See (Vatican City State)', 'Europe', 3538);
INSERT INTO `country` VALUES ('VCT', 'Saint Vincent and the Grenadines', 'North America', 3066);
INSERT INTO `country` VALUES ('VEN', 'Venezuela', 'South America', 3539);
INSERT INTO `country` VALUES ('VGB', 'Virgin Islands, British',  'North America', 537);
INSERT INTO `country` VALUES ('VIR', 'Virgin Islands, U.S.', 'North America', 4067);
INSERT INTO `country` VALUES ('VNM', 'Vietnam', 'Asia', 3770);
INSERT INTO `country` VALUES ('VUT', 'Vanuatu', 'Oceania', 3537);
INSERT INTO `country` VALUES ('WLF', 'Wallis and Futuna', 'Oceania', 3536);
INSERT INTO `country` VALUES ('WSM', 'Samoa', 'Oceania', 3169);
INSERT INTO `country` VALUES ('YEM', 'Yemen', 'Asia', 1780);
INSERT INTO `country` VALUES ('YUG', 'Yugoslavia', 'Europe', 1792);
INSERT INTO `country` VALUES ('ZAF', 'South Africa', 'Africa', 716);
INSERT INTO `country` VALUES ('ZMB', 'Zambia', 'Africa', 3162);
INSERT INTO `country` VALUES ('ZWE', 'Zimbabwe', 'Africa', 4068);
