INSERT INTO `luggage_item` VALUES (1,'Паспорт /Лична карта/','Документи');
INSERT INTO `luggage_item` VALUES (2,'Бордна карта','Документи');
INSERT INTO `luggage_item` VALUES (3,'Виза','Документи');
INSERT INTO `luggage_item` VALUES (4,'Кредитна/Дебитна/ карта', 'Документи');
INSERT INTO `luggage_item` VALUES (5,'Здравна застраховка','Devices');
INSERT INTO `luggage_item` VALUES (6,'Бордна карта','Clothes');
INSERT INTO `luggage_item` VALUES (7,'Джобна /Пътна/ карта','Clothes');
INSERT INTO `luggage_item` VALUES (8,'Тениски','Clothes');
INSERT INTO `luggage_item` VALUES (9,'Вратовръзка','Clothes');
INSERT INTO `luggage_item` VALUES (10,'Аналгин','Medicines');
